import BaseLayout from '@/containers/Layout/BaseLayout';
import Home from '@/containers/Home';

import Head from 'next/head';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Home />
      </BaseLayout>
    </>
  );
}
