import BaseLayout from '@/containers/Layout/BaseLayout';
import Profile from '@/containers/Profile';
import Head from 'next/head';

const ProfilePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <Profile />
      </BaseLayout>
    </>
  );
};

export default ProfilePage;
