import StackLayout from '@/containers/Layout/StackLayout';
import User from '@/containers/User';
import Head from 'next/head';

const UserPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StackLayout
        useHeader={true}
        headerOptions={{
          title: 'You Gosu',
        }}
      >
        <User />
      </StackLayout>
    </>
  );
};

export default UserPage;
